### ISSUE TITLE
apt-get error when building image: Unable to correct problems, you have held broken package

### ISSUE THREAD

**Issue by snobear** [rfkrocktk/docker-puppetmaster#26]
Hi,
I'm getting the following when building

```
$ docker build .
Step 13 : RUN apt-get update -q 2 && DEBIAN_FRONTEND=noninteractive     apt-get install --yes -q 2 puppetmaster=$PUPPET_VERSION puppet=$PUPPET_VERSION         nginx-extras passenger >/dev/null
 ---> Running in c19dc1e1d796
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -q 2 && DEBIAN_FRONTEND=noninteractive     apt-get install --yes -q 2 puppetmaster=$PUPPET_VERSION puppet=$PUPPET_VERSION         nginx-extras passenger >/dev/null' returned a non-zero code: 100
```

I took out the `PUPPET_VERSION` references completely and it runs fine. I'm not real familiar with apt-get, but I assume the version currently pinned isn't the latest in the apt repo?

**Comment by naftulikay** [comment]
The reason why we "pin" the image to the latest version of Puppet is for security and reuse. 

If you want the latest version, please submit a pull request with the PUPPET_VERSION updated in the build. I'd do the following to determine the latest version:
1. Use a VM environment like Vagrant and launch an Ubuntu 14.04 base image. Alternatively, you can do the same thing with an Ubuntu Docker image for the same version.
2. Install the Puppet Labs repository as per the Dockerfile in this repository.
3. Do an apt-get update.
4. Find the latest version of the Puppet Debian package and update the Dockerfile here to pin to that.

The reason you want pinning is so that downstream users like yourself can easily determine which version of Puppet is running in a given image build. If a Puppet CVE comes out, all I need to do as the maintainer is update the `PUPPET_VERSION`, rebake my image, tag, and upload.

**Comment by snobear** [comment]
The problem is that building the Dockerfile right out of the box did not work and failed with the error I mentioned, so it doesn't seem like pinning to a specific puppet version works as intended with apt-get. Or maybe I'm doing something wrong.  Anyway, just thought I'd mention it and what my fix was in case others not familiar with apt-get hit that error.

**Comment by naftulikay** [comment]
Thanks for your response.

If there is, in fact, a later release of Puppet, it would be ideal to rebuild the image now to incorporate it.
